language: ruby
rvm:
  - 1.9.3
before_install:
  - rvm get head
  - rvm alias delete default
  - hash -r
install: gem install dtf
before_script:
  - unset BUNDLE_GEMFILE
script: 'dtf --text fast/*'
notifications:
  irc:
    channels:
      - "irc.freenode.org#rvm-test"
      - "irc.freenode.org#rvm"
  email:
    recipients:
      - mpapis@gmail.com
      - me@deryldoucette.com
    on_failure: change
